"""create incidents

Revision ID: ee06ce8fbc8f
Revises:
Create Date: 2026-09-27 22:20:58.218252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ee06ce8fbc8f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('job_name', sa.String(length=200), nullable=False),
    sa.Column('log', sa.Text(), nullable=False),
    sa.Column('exit_code', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("job_name ~ '[^[:space:]]'", name='ck_incidents_job_name_not_blank'),
    sa.CheckConstraint("log ~ '[^[:space:]]'", name='ck_incidents_log_not_blank'),
    sa.CheckConstraint('octet_length(log) <= 65536', name='ck_incidents_log_max_bytes'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('incidents')
    # ### end Alembic commands ###
